#baseurl: "/2017"

title: "BuildingBloCS"
tagline: "High School Computing Conference"
date: "Wed 2 June - Fri 4 June"
location: "Online / In Person"

exclude:
  - README.md
  - assets/sass
  - package.json
  - package-lock.json
  - node_modules/
  - Gruntfile.js
